/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Compute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMPUTE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComputeImpl <em>Compute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComputeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompute()
   * @generated
   */
  int COMPUTE = 1;

  /**
   * The number of structural features of the '<em>Compute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ParametroImpl <em>Parametro</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ParametroImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParametro()
   * @generated
   */
  int PARAMETRO = 2;

  /**
   * The feature id for the '<em><b>Exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRO__EXP = COMPUTE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRO__VAR = COMPUTE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Parametro</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRO_FEATURE_COUNT = COMPUTE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RecursivoImpl <em>Recursivo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RecursivoImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecursivo()
   * @generated
   */
  int RECURSIVO = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSIVO__NAME = 0;

  /**
   * The number of structural features of the '<em>Recursivo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSIVO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparacaoImpl <em>Comparacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComparacaoImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparacao()
   * @generated
   */
  int COMPARACAO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO__NAME = 0;

  /**
   * The number of structural features of the '<em>Comparacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Model#getCompute <em>Compute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Compute</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getCompute()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Compute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Compute <em>Compute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compute</em>'.
   * @see org.xtext.example.mydsl.myDsl.Compute
   * @generated
   */
  EClass getCompute();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Parametro <em>Parametro</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parametro</em>'.
   * @see org.xtext.example.mydsl.myDsl.Parametro
   * @generated
   */
  EClass getParametro();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Parametro#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exp</em>'.
   * @see org.xtext.example.mydsl.myDsl.Parametro#getExp()
   * @see #getParametro()
   * @generated
   */
  EAttribute getParametro_Exp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Parametro#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.example.mydsl.myDsl.Parametro#getVar()
   * @see #getParametro()
   * @generated
   */
  EAttribute getParametro_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Recursivo <em>Recursivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recursivo</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recursivo
   * @generated
   */
  EClass getRecursivo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Recursivo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Recursivo#getName()
   * @see #getRecursivo()
   * @generated
   */
  EAttribute getRecursivo_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Comparacao <em>Comparacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparacao</em>'.
   * @see org.xtext.example.mydsl.myDsl.Comparacao
   * @generated
   */
  EClass getComparacao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Comparacao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Comparacao#getName()
   * @see #getComparacao()
   * @generated
   */
  EAttribute getComparacao_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Compute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMPUTE = eINSTANCE.getModel_Compute();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComputeImpl <em>Compute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComputeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompute()
     * @generated
     */
    EClass COMPUTE = eINSTANCE.getCompute();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ParametroImpl <em>Parametro</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ParametroImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParametro()
     * @generated
     */
    EClass PARAMETRO = eINSTANCE.getParametro();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRO__EXP = eINSTANCE.getParametro_Exp();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRO__VAR = eINSTANCE.getParametro_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RecursivoImpl <em>Recursivo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RecursivoImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRecursivo()
     * @generated
     */
    EClass RECURSIVO = eINSTANCE.getRecursivo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECURSIVO__NAME = eINSTANCE.getRecursivo_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparacaoImpl <em>Comparacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComparacaoImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparacao()
     * @generated
     */
    EClass COMPARACAO = eINSTANCE.getComparacao();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARACAO__NAME = eINSTANCE.getComparacao_Name();

  }

} //MyDslPackage
